version: 1
builder:
  configs:
  - platform: ios
    scheme: IdentifiedCollections
  - platform: tvos
    scheme: IdentifiedCollections
  - platform: watchos
    scheme: IdentifiedCollections
  - documentation_targets: [IdentifiedCollections]
